//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("BanquetesElijaModel", "FK__UserDevic__Authe__20C1E124", "Authentication", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FreakyByte.Elija.DataAccess.Model.Authentication), "UserDevice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FreakyByte.Elija.DataAccess.Model.UserDevice), true)]
[assembly: EdmRelationshipAttribute("BanquetesElijaModel", "FK__UserDevic__Devic__21B6055D", "Device", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FreakyByte.Elija.DataAccess.Model.Device), "UserDevice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FreakyByte.Elija.DataAccess.Model.UserDevice), true)]
[assembly: EdmRelationshipAttribute("BanquetesElijaModel", "FK__Image__ImageType__1DE57479", "ImageType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FreakyByte.Elija.DataAccess.Model.ImageType), "Image", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FreakyByte.Elija.DataAccess.Model.Image), true)]
[assembly: EdmRelationshipAttribute("BanquetesElijaModel", "FK__Image__NodeId__1ED998B2", "Node", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FreakyByte.Elija.DataAccess.Model.Node), "Image", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FreakyByte.Elija.DataAccess.Model.Image), true)]
[assembly: EdmRelationshipAttribute("BanquetesElijaModel", "FK__Node__NodeTypeId__1FCDBCEB", "NodeType", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FreakyByte.Elija.DataAccess.Model.NodeType), "Node", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FreakyByte.Elija.DataAccess.Model.Node), true)]
[assembly: EdmRelationshipAttribute("BanquetesElijaModel", "FK__UserDevic__UserI__22AA2996", "User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(FreakyByte.Elija.DataAccess.Model.User), "UserDevice", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(FreakyByte.Elija.DataAccess.Model.UserDevice), true)]

#endregion

namespace FreakyByte.Elija.DataAccess.Model
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ElijaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ElijaEntities usando la cadena de conexión encontrada en la sección 'ElijaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public ElijaEntities() : base("name=ElijaEntities", "ElijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ElijaEntities.
        /// </summary>
        public ElijaEntities(string connectionString) : base(connectionString, "ElijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ElijaEntities.
        /// </summary>
        public ElijaEntities(EntityConnection connection) : base(connection, "ElijaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Authentication> Authentication
        {
            get
            {
                if ((_Authentication == null))
                {
                    _Authentication = base.CreateObjectSet<Authentication>("Authentication");
                }
                return _Authentication;
            }
        }
        private ObjectSet<Authentication> _Authentication;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Device> Device
        {
            get
            {
                if ((_Device == null))
                {
                    _Device = base.CreateObjectSet<Device>("Device");
                }
                return _Device;
            }
        }
        private ObjectSet<Device> _Device;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Image> Image
        {
            get
            {
                if ((_Image == null))
                {
                    _Image = base.CreateObjectSet<Image>("Image");
                }
                return _Image;
            }
        }
        private ObjectSet<Image> _Image;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<ImageType> ImageType
        {
            get
            {
                if ((_ImageType == null))
                {
                    _ImageType = base.CreateObjectSet<ImageType>("ImageType");
                }
                return _ImageType;
            }
        }
        private ObjectSet<ImageType> _ImageType;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Node> Node
        {
            get
            {
                if ((_Node == null))
                {
                    _Node = base.CreateObjectSet<Node>("Node");
                }
                return _Node;
            }
        }
        private ObjectSet<Node> _Node;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<NodeType> NodeType
        {
            get
            {
                if ((_NodeType == null))
                {
                    _NodeType = base.CreateObjectSet<NodeType>("NodeType");
                }
                return _NodeType;
            }
        }
        private ObjectSet<NodeType> _NodeType;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<UserDevice> UserDevice
        {
            get
            {
                if ((_UserDevice == null))
                {
                    _UserDevice = base.CreateObjectSet<UserDevice>("UserDevice");
                }
                return _UserDevice;
            }
        }
        private ObjectSet<UserDevice> _UserDevice;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Authentication. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAuthentication(Authentication authentication)
        {
            base.AddObject("Authentication", authentication);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Device. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToDevice(Device device)
        {
            base.AddObject("Device", device);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Image. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToImage(Image image)
        {
            base.AddObject("Image", image);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet ImageType. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToImageType(ImageType imageType)
        {
            base.AddObject("ImageType", imageType);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Node. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToNode(Node node)
        {
            base.AddObject("Node", node);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet NodeType. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToNodeType(NodeType nodeType)
        {
            base.AddObject("NodeType", nodeType);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet User. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet UserDevice. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToUserDevice(UserDevice userDevice)
        {
            base.AddObject("UserDevice", userDevice);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BanquetesElijaModel", Name="Authentication")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Authentication : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Authentication.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad Id.</param>
        /// <param name="token">Valor inicial de la propiedad Token.</param>
        /// <param name="expiration">Valor inicial de la propiedad Expiration.</param>
        public static Authentication CreateAuthentication(global::System.Int32 id, global::System.String token, global::System.DateTime expiration)
        {
            Authentication authentication = new Authentication();
            authentication.Id = id;
            authentication.Token = token;
            authentication.Expiration = expiration;
            return authentication;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Token
        {
            get
            {
                return _Token;
            }
            set
            {
                OnTokenChanging(value);
                ReportPropertyChanging("Token");
                _Token = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Token");
                OnTokenChanged();
            }
        }
        private global::System.String _Token;
        partial void OnTokenChanging(global::System.String value);
        partial void OnTokenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Expiration
        {
            get
            {
                return _Expiration;
            }
            set
            {
                OnExpirationChanging(value);
                ReportPropertyChanging("Expiration");
                _Expiration = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Expiration");
                OnExpirationChanged();
            }
        }
        private global::System.DateTime _Expiration;
        partial void OnExpirationChanging(global::System.DateTime value);
        partial void OnExpirationChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__UserDevic__Authe__20C1E124", "UserDevice")]
        public EntityCollection<UserDevice> UserDevice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserDevice>("BanquetesElijaModel.FK__UserDevic__Authe__20C1E124", "UserDevice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserDevice>("BanquetesElijaModel.FK__UserDevic__Authe__20C1E124", "UserDevice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BanquetesElijaModel", Name="Device")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Device : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Device.
        /// </summary>
        /// <param name="deviceId">Valor inicial de la propiedad DeviceId.</param>
        /// <param name="brand">Valor inicial de la propiedad Brand.</param>
        /// <param name="device1">Valor inicial de la propiedad Device1.</param>
        /// <param name="display">Valor inicial de la propiedad Display.</param>
        /// <param name="manufacturer">Valor inicial de la propiedad Manufacturer.</param>
        /// <param name="model">Valor inicial de la propiedad Model.</param>
        /// <param name="product">Valor inicial de la propiedad Product.</param>
        /// <param name="androidId">Valor inicial de la propiedad AndroidId.</param>
        /// <param name="osVersion">Valor inicial de la propiedad OsVersion.</param>
        /// <param name="codeVersion">Valor inicial de la propiedad CodeVersion.</param>
        /// <param name="releaseVersion">Valor inicial de la propiedad ReleaseVersion.</param>
        /// <param name="isPhone">Valor inicial de la propiedad IsPhone.</param>
        /// <param name="registrationDate">Valor inicial de la propiedad RegistrationDate.</param>
        public static Device CreateDevice(global::System.Int32 deviceId, global::System.String brand, global::System.String device1, global::System.Int32 display, global::System.String manufacturer, global::System.String model, global::System.String product, global::System.String androidId, global::System.String osVersion, global::System.String codeVersion, global::System.String releaseVersion, global::System.Boolean isPhone, global::System.DateTime registrationDate)
        {
            Device device = new Device();
            device.DeviceId = deviceId;
            device.Brand = brand;
            device.Device1 = device1;
            device.Display = display;
            device.Manufacturer = manufacturer;
            device.Model = model;
            device.Product = product;
            device.AndroidId = androidId;
            device.OsVersion = osVersion;
            device.CodeVersion = codeVersion;
            device.ReleaseVersion = releaseVersion;
            device.IsPhone = isPhone;
            device.RegistrationDate = registrationDate;
            return device;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeviceId
        {
            get
            {
                return _DeviceId;
            }
            set
            {
                if (_DeviceId != value)
                {
                    OnDeviceIdChanging(value);
                    ReportPropertyChanging("DeviceId");
                    _DeviceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DeviceId");
                    OnDeviceIdChanged();
                }
            }
        }
        private global::System.Int32 _DeviceId;
        partial void OnDeviceIdChanging(global::System.Int32 value);
        partial void OnDeviceIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IMEI
        {
            get
            {
                return _IMEI;
            }
            set
            {
                OnIMEIChanging(value);
                ReportPropertyChanging("IMEI");
                _IMEI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IMEI");
                OnIMEIChanged();
            }
        }
        private Nullable<global::System.Int32> _IMEI;
        partial void OnIMEIChanging(Nullable<global::System.Int32> value);
        partial void OnIMEIChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Device1
        {
            get
            {
                return _Device1;
            }
            set
            {
                OnDevice1Changing(value);
                ReportPropertyChanging("Device1");
                _Device1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Device1");
                OnDevice1Changed();
            }
        }
        private global::System.String _Device1;
        partial void OnDevice1Changing(global::System.String value);
        partial void OnDevice1Changed();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Display
        {
            get
            {
                return _Display;
            }
            set
            {
                OnDisplayChanging(value);
                ReportPropertyChanging("Display");
                _Display = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Display");
                OnDisplayChanged();
            }
        }
        private global::System.Int32 _Display;
        partial void OnDisplayChanging(global::System.Int32 value);
        partial void OnDisplayChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Manufacturer
        {
            get
            {
                return _Manufacturer;
            }
            set
            {
                OnManufacturerChanging(value);
                ReportPropertyChanging("Manufacturer");
                _Manufacturer = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Manufacturer");
                OnManufacturerChanged();
            }
        }
        private global::System.String _Manufacturer;
        partial void OnManufacturerChanging(global::System.String value);
        partial void OnManufacturerChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Model
        {
            get
            {
                return _Model;
            }
            set
            {
                OnModelChanging(value);
                ReportPropertyChanging("Model");
                _Model = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Model");
                OnModelChanged();
            }
        }
        private global::System.String _Model;
        partial void OnModelChanging(global::System.String value);
        partial void OnModelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Product
        {
            get
            {
                return _Product;
            }
            set
            {
                OnProductChanging(value);
                ReportPropertyChanging("Product");
                _Product = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Product");
                OnProductChanged();
            }
        }
        private global::System.String _Product;
        partial void OnProductChanging(global::System.String value);
        partial void OnProductChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Operator
        {
            get
            {
                return _Operator;
            }
            set
            {
                OnOperatorChanging(value);
                ReportPropertyChanging("Operator");
                _Operator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Operator");
                OnOperatorChanged();
            }
        }
        private global::System.String _Operator;
        partial void OnOperatorChanging(global::System.String value);
        partial void OnOperatorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String AndroidId
        {
            get
            {
                return _AndroidId;
            }
            set
            {
                OnAndroidIdChanging(value);
                ReportPropertyChanging("AndroidId");
                _AndroidId = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("AndroidId");
                OnAndroidIdChanged();
            }
        }
        private global::System.String _AndroidId;
        partial void OnAndroidIdChanging(global::System.String value);
        partial void OnAndroidIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OsVersion
        {
            get
            {
                return _OsVersion;
            }
            set
            {
                OnOsVersionChanging(value);
                ReportPropertyChanging("OsVersion");
                _OsVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OsVersion");
                OnOsVersionChanged();
            }
        }
        private global::System.String _OsVersion;
        partial void OnOsVersionChanging(global::System.String value);
        partial void OnOsVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CodeVersion
        {
            get
            {
                return _CodeVersion;
            }
            set
            {
                OnCodeVersionChanging(value);
                ReportPropertyChanging("CodeVersion");
                _CodeVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CodeVersion");
                OnCodeVersionChanged();
            }
        }
        private global::System.String _CodeVersion;
        partial void OnCodeVersionChanging(global::System.String value);
        partial void OnCodeVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReleaseVersion
        {
            get
            {
                return _ReleaseVersion;
            }
            set
            {
                OnReleaseVersionChanging(value);
                ReportPropertyChanging("ReleaseVersion");
                _ReleaseVersion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReleaseVersion");
                OnReleaseVersionChanged();
            }
        }
        private global::System.String _ReleaseVersion;
        partial void OnReleaseVersionChanging(global::System.String value);
        partial void OnReleaseVersionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsPhone
        {
            get
            {
                return _IsPhone;
            }
            set
            {
                OnIsPhoneChanging(value);
                ReportPropertyChanging("IsPhone");
                _IsPhone = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsPhone");
                OnIsPhoneChanged();
            }
        }
        private global::System.Boolean _IsPhone;
        partial void OnIsPhoneChanging(global::System.Boolean value);
        partial void OnIsPhoneChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private global::System.DateTime _RegistrationDate;
        partial void OnRegistrationDateChanging(global::System.DateTime value);
        partial void OnRegistrationDateChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__UserDevic__Devic__21B6055D", "UserDevice")]
        public EntityCollection<UserDevice> UserDevice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserDevice>("BanquetesElijaModel.FK__UserDevic__Devic__21B6055D", "UserDevice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserDevice>("BanquetesElijaModel.FK__UserDevic__Devic__21B6055D", "UserDevice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BanquetesElijaModel", Name="Image")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Image : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Image.
        /// </summary>
        /// <param name="imageId">Valor inicial de la propiedad ImageId.</param>
        /// <param name="url">Valor inicial de la propiedad Url.</param>
        /// <param name="width">Valor inicial de la propiedad Width.</param>
        /// <param name="height">Valor inicial de la propiedad Height.</param>
        /// <param name="size">Valor inicial de la propiedad Size.</param>
        /// <param name="imageTypeId">Valor inicial de la propiedad ImageTypeId.</param>
        /// <param name="nodeId">Valor inicial de la propiedad NodeId.</param>
        public static Image CreateImage(global::System.Int32 imageId, global::System.String url, global::System.Int32 width, global::System.Int32 height, global::System.Int32 size, global::System.Int32 imageTypeId, global::System.Int32 nodeId)
        {
            Image image = new Image();
            image.ImageId = imageId;
            image.Url = url;
            image.Width = width;
            image.Height = height;
            image.Size = size;
            image.ImageTypeId = imageTypeId;
            image.NodeId = nodeId;
            return image;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageId
        {
            get
            {
                return _ImageId;
            }
            set
            {
                if (_ImageId != value)
                {
                    OnImageIdChanging(value);
                    ReportPropertyChanging("ImageId");
                    _ImageId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ImageId");
                    OnImageIdChanged();
                }
            }
        }
        private global::System.Int32 _ImageId;
        partial void OnImageIdChanging(global::System.Int32 value);
        partial void OnImageIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Width
        {
            get
            {
                return _Width;
            }
            set
            {
                OnWidthChanging(value);
                ReportPropertyChanging("Width");
                _Width = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Width");
                OnWidthChanged();
            }
        }
        private global::System.Int32 _Width;
        partial void OnWidthChanging(global::System.Int32 value);
        partial void OnWidthChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Height
        {
            get
            {
                return _Height;
            }
            set
            {
                OnHeightChanging(value);
                ReportPropertyChanging("Height");
                _Height = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Height");
                OnHeightChanged();
            }
        }
        private global::System.Int32 _Height;
        partial void OnHeightChanging(global::System.Int32 value);
        partial void OnHeightChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Size
        {
            get
            {
                return _Size;
            }
            set
            {
                OnSizeChanging(value);
                ReportPropertyChanging("Size");
                _Size = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Size");
                OnSizeChanged();
            }
        }
        private global::System.Int32 _Size;
        partial void OnSizeChanging(global::System.Int32 value);
        partial void OnSizeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageTypeId
        {
            get
            {
                return _ImageTypeId;
            }
            set
            {
                OnImageTypeIdChanging(value);
                ReportPropertyChanging("ImageTypeId");
                _ImageTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ImageTypeId");
                OnImageTypeIdChanged();
            }
        }
        private global::System.Int32 _ImageTypeId;
        partial void OnImageTypeIdChanging(global::System.Int32 value);
        partial void OnImageTypeIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NodeId
        {
            get
            {
                return _NodeId;
            }
            set
            {
                OnNodeIdChanging(value);
                ReportPropertyChanging("NodeId");
                _NodeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeId");
                OnNodeIdChanged();
            }
        }
        private global::System.Int32 _NodeId;
        partial void OnNodeIdChanging(global::System.Int32 value);
        partial void OnNodeIdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__Image__ImageType__1DE57479", "ImageType")]
        public ImageType ImageType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ImageType>("BanquetesElijaModel.FK__Image__ImageType__1DE57479", "ImageType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ImageType>("BanquetesElijaModel.FK__Image__ImageType__1DE57479", "ImageType").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ImageType> ImageTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ImageType>("BanquetesElijaModel.FK__Image__ImageType__1DE57479", "ImageType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ImageType>("BanquetesElijaModel.FK__Image__ImageType__1DE57479", "ImageType", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__Image__NodeId__1ED998B2", "Node")]
        public Node Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Node>("BanquetesElijaModel.FK__Image__NodeId__1ED998B2", "Node").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Node>("BanquetesElijaModel.FK__Image__NodeId__1ED998B2", "Node").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Node> NodeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Node>("BanquetesElijaModel.FK__Image__NodeId__1ED998B2", "Node");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Node>("BanquetesElijaModel.FK__Image__NodeId__1ED998B2", "Node", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BanquetesElijaModel", Name="ImageType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ImageType : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto ImageType.
        /// </summary>
        /// <param name="imageTypeId">Valor inicial de la propiedad ImageTypeId.</param>
        /// <param name="description">Valor inicial de la propiedad Description.</param>
        public static ImageType CreateImageType(global::System.Int32 imageTypeId, global::System.String description)
        {
            ImageType imageType = new ImageType();
            imageType.ImageTypeId = imageTypeId;
            imageType.Description = description;
            return imageType;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ImageTypeId
        {
            get
            {
                return _ImageTypeId;
            }
            set
            {
                if (_ImageTypeId != value)
                {
                    OnImageTypeIdChanging(value);
                    ReportPropertyChanging("ImageTypeId");
                    _ImageTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ImageTypeId");
                    OnImageTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _ImageTypeId;
        partial void OnImageTypeIdChanging(global::System.Int32 value);
        partial void OnImageTypeIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__Image__ImageType__1DE57479", "Image")]
        public EntityCollection<Image> Image
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Image>("BanquetesElijaModel.FK__Image__ImageType__1DE57479", "Image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Image>("BanquetesElijaModel.FK__Image__ImageType__1DE57479", "Image", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BanquetesElijaModel", Name="Node")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Node : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Node.
        /// </summary>
        /// <param name="nodeId">Valor inicial de la propiedad NodeId.</param>
        /// <param name="level">Valor inicial de la propiedad Level.</param>
        /// <param name="name">Valor inicial de la propiedad Name.</param>
        /// <param name="nodeTypeId">Valor inicial de la propiedad NodeTypeId.</param>
        /// <param name="isActive">Valor inicial de la propiedad IsActive.</param>
        /// <param name="createdAt">Valor inicial de la propiedad CreatedAt.</param>
        public static Node CreateNode(global::System.Int32 nodeId, global::System.Int32 level, global::System.String name, global::System.Int32 nodeTypeId, global::System.Boolean isActive, global::System.DateTime createdAt)
        {
            Node node = new Node();
            node.NodeId = nodeId;
            node.Level = level;
            node.Name = name;
            node.NodeTypeId = nodeTypeId;
            node.IsActive = isActive;
            node.CreatedAt = createdAt;
            return node;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NodeId
        {
            get
            {
                return _NodeId;
            }
            set
            {
                if (_NodeId != value)
                {
                    OnNodeIdChanging(value);
                    ReportPropertyChanging("NodeId");
                    _NodeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NodeId");
                    OnNodeIdChanged();
                }
            }
        }
        private global::System.Int32 _NodeId;
        partial void OnNodeIdChanging(global::System.Int32 value);
        partial void OnNodeIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ParentId
        {
            get
            {
                return _ParentId;
            }
            set
            {
                OnParentIdChanging(value);
                ReportPropertyChanging("ParentId");
                _ParentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ParentId");
                OnParentIdChanged();
            }
        }
        private Nullable<global::System.Int32> _ParentId;
        partial void OnParentIdChanging(Nullable<global::System.Int32> value);
        partial void OnParentIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Level
        {
            get
            {
                return _Level;
            }
            set
            {
                OnLevelChanging(value);
                ReportPropertyChanging("Level");
                _Level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Level");
                OnLevelChanged();
            }
        }
        private global::System.Int32 _Level;
        partial void OnLevelChanging(global::System.Int32 value);
        partial void OnLevelChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Text
        {
            get
            {
                return _Text;
            }
            set
            {
                OnTextChanging(value);
                ReportPropertyChanging("Text");
                _Text = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Text");
                OnTextChanged();
            }
        }
        private global::System.String _Text;
        partial void OnTextChanging(global::System.String value);
        partial void OnTextChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NodeTypeId
        {
            get
            {
                return _NodeTypeId;
            }
            set
            {
                OnNodeTypeIdChanging(value);
                ReportPropertyChanging("NodeTypeId");
                _NodeTypeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeTypeId");
                OnNodeTypeIdChanged();
            }
        }
        private global::System.Int32 _NodeTypeId;
        partial void OnNodeTypeIdChanging(global::System.Int32 value);
        partial void OnNodeTypeIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsActive
        {
            get
            {
                return _IsActive;
            }
            set
            {
                OnIsActiveChanging(value);
                ReportPropertyChanging("IsActive");
                _IsActive = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsActive");
                OnIsActiveChanged();
            }
        }
        private global::System.Boolean _IsActive;
        partial void OnIsActiveChanging(global::System.Boolean value);
        partial void OnIsActiveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__Image__NodeId__1ED998B2", "Image")]
        public EntityCollection<Image> Image
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Image>("BanquetesElijaModel.FK__Image__NodeId__1ED998B2", "Image");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Image>("BanquetesElijaModel.FK__Image__NodeId__1ED998B2", "Image", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__Node__NodeTypeId__1FCDBCEB", "NodeType")]
        public NodeType NodeType
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeType>("BanquetesElijaModel.FK__Node__NodeTypeId__1FCDBCEB", "NodeType").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeType>("BanquetesElijaModel.FK__Node__NodeTypeId__1FCDBCEB", "NodeType").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<NodeType> NodeTypeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<NodeType>("BanquetesElijaModel.FK__Node__NodeTypeId__1FCDBCEB", "NodeType");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<NodeType>("BanquetesElijaModel.FK__Node__NodeTypeId__1FCDBCEB", "NodeType", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BanquetesElijaModel", Name="NodeType")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NodeType : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto NodeType.
        /// </summary>
        /// <param name="nodeTypeId">Valor inicial de la propiedad NodeTypeId.</param>
        /// <param name="description">Valor inicial de la propiedad Description.</param>
        public static NodeType CreateNodeType(global::System.Int32 nodeTypeId, global::System.String description)
        {
            NodeType nodeType = new NodeType();
            nodeType.NodeTypeId = nodeTypeId;
            nodeType.Description = description;
            return nodeType;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NodeTypeId
        {
            get
            {
                return _NodeTypeId;
            }
            set
            {
                if (_NodeTypeId != value)
                {
                    OnNodeTypeIdChanging(value);
                    ReportPropertyChanging("NodeTypeId");
                    _NodeTypeId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NodeTypeId");
                    OnNodeTypeIdChanged();
                }
            }
        }
        private global::System.Int32 _NodeTypeId;
        partial void OnNodeTypeIdChanging(global::System.Int32 value);
        partial void OnNodeTypeIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__Node__NodeTypeId__1FCDBCEB", "Node")]
        public EntityCollection<Node> Node
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Node>("BanquetesElijaModel.FK__Node__NodeTypeId__1FCDBCEB", "Node");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Node>("BanquetesElijaModel.FK__Node__NodeTypeId__1FCDBCEB", "Node", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BanquetesElijaModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto User.
        /// </summary>
        /// <param name="userId">Valor inicial de la propiedad UserId.</param>
        public static User CreateUser(global::System.Int32 userId)
        {
            User user = new User();
            user.UserId = userId;
            return user;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                if (_UserId != value)
                {
                    OnUserIdChanging(value);
                    ReportPropertyChanging("UserId");
                    _UserId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserId");
                    OnUserIdChanged();
                }
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FacebookId
        {
            get
            {
                return _FacebookId;
            }
            set
            {
                OnFacebookIdChanging(value);
                ReportPropertyChanging("FacebookId");
                _FacebookId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FacebookId");
                OnFacebookIdChanged();
            }
        }
        private Nullable<global::System.Int32> _FacebookId;
        partial void OnFacebookIdChanging(Nullable<global::System.Int32> value);
        partial void OnFacebookIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Age
        {
            get
            {
                return _Age;
            }
            set
            {
                OnAgeChanging(value);
                ReportPropertyChanging("Age");
                _Age = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Age");
                OnAgeChanged();
            }
        }
        private Nullable<global::System.Int32> _Age;
        partial void OnAgeChanging(Nullable<global::System.Int32> value);
        partial void OnAgeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FacebookLink
        {
            get
            {
                return _FacebookLink;
            }
            set
            {
                OnFacebookLinkChanging(value);
                ReportPropertyChanging("FacebookLink");
                _FacebookLink = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FacebookLink");
                OnFacebookLinkChanged();
            }
        }
        private global::System.String _FacebookLink;
        partial void OnFacebookLinkChanging(global::System.String value);
        partial void OnFacebookLinkChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneHome
        {
            get
            {
                return _TelephoneHome;
            }
            set
            {
                OnTelephoneHomeChanging(value);
                ReportPropertyChanging("TelephoneHome");
                _TelephoneHome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneHome");
                OnTelephoneHomeChanged();
            }
        }
        private global::System.String _TelephoneHome;
        partial void OnTelephoneHomeChanging(global::System.String value);
        partial void OnTelephoneHomeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneOffice
        {
            get
            {
                return _TelephoneOffice;
            }
            set
            {
                OnTelephoneOfficeChanging(value);
                ReportPropertyChanging("TelephoneOffice");
                _TelephoneOffice = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneOffice");
                OnTelephoneOfficeChanged();
            }
        }
        private global::System.String _TelephoneOffice;
        partial void OnTelephoneOfficeChanging(global::System.String value);
        partial void OnTelephoneOfficeChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String TelephoneMobile
        {
            get
            {
                return _TelephoneMobile;
            }
            set
            {
                OnTelephoneMobileChanging(value);
                ReportPropertyChanging("TelephoneMobile");
                _TelephoneMobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("TelephoneMobile");
                OnTelephoneMobileChanged();
            }
        }
        private global::System.String _TelephoneMobile;
        partial void OnTelephoneMobileChanging(global::System.String value);
        partial void OnTelephoneMobileChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> RegistrationDate
        {
            get
            {
                return _RegistrationDate;
            }
            set
            {
                OnRegistrationDateChanging(value);
                ReportPropertyChanging("RegistrationDate");
                _RegistrationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RegistrationDate");
                OnRegistrationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _RegistrationDate;
        partial void OnRegistrationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnRegistrationDateChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__UserDevic__UserI__22AA2996", "UserDevice")]
        public EntityCollection<UserDevice> UserDevice
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<UserDevice>("BanquetesElijaModel.FK__UserDevic__UserI__22AA2996", "UserDevice");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<UserDevice>("BanquetesElijaModel.FK__UserDevic__UserI__22AA2996", "UserDevice", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BanquetesElijaModel", Name="UserDevice")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserDevice : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto UserDevice.
        /// </summary>
        /// <param name="userDeviceId">Valor inicial de la propiedad UserDeviceId.</param>
        /// <param name="userId">Valor inicial de la propiedad UserId.</param>
        /// <param name="deviceId">Valor inicial de la propiedad DeviceId.</param>
        /// <param name="createdAt">Valor inicial de la propiedad CreatedAt.</param>
        /// <param name="lastActivityDate">Valor inicial de la propiedad LastActivityDate.</param>
        /// <param name="authenticationId">Valor inicial de la propiedad AuthenticationId.</param>
        public static UserDevice CreateUserDevice(global::System.Int32 userDeviceId, global::System.Int32 userId, global::System.Int32 deviceId, global::System.DateTime createdAt, global::System.DateTime lastActivityDate, global::System.Int32 authenticationId)
        {
            UserDevice userDevice = new UserDevice();
            userDevice.UserDeviceId = userDeviceId;
            userDevice.UserId = userId;
            userDevice.DeviceId = deviceId;
            userDevice.CreatedAt = createdAt;
            userDevice.LastActivityDate = lastActivityDate;
            userDevice.AuthenticationId = authenticationId;
            return userDevice;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserDeviceId
        {
            get
            {
                return _UserDeviceId;
            }
            set
            {
                if (_UserDeviceId != value)
                {
                    OnUserDeviceIdChanging(value);
                    ReportPropertyChanging("UserDeviceId");
                    _UserDeviceId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("UserDeviceId");
                    OnUserDeviceIdChanged();
                }
            }
        }
        private global::System.Int32 _UserDeviceId;
        partial void OnUserDeviceIdChanging(global::System.Int32 value);
        partial void OnUserDeviceIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserId
        {
            get
            {
                return _UserId;
            }
            set
            {
                OnUserIdChanging(value);
                ReportPropertyChanging("UserId");
                _UserId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserId");
                OnUserIdChanged();
            }
        }
        private global::System.Int32 _UserId;
        partial void OnUserIdChanging(global::System.Int32 value);
        partial void OnUserIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DeviceId
        {
            get
            {
                return _DeviceId;
            }
            set
            {
                OnDeviceIdChanging(value);
                ReportPropertyChanging("DeviceId");
                _DeviceId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeviceId");
                OnDeviceIdChanged();
            }
        }
        private global::System.Int32 _DeviceId;
        partial void OnDeviceIdChanging(global::System.Int32 value);
        partial void OnDeviceIdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedAt
        {
            get
            {
                return _CreatedAt;
            }
            set
            {
                OnCreatedAtChanging(value);
                ReportPropertyChanging("CreatedAt");
                _CreatedAt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedAt");
                OnCreatedAtChanged();
            }
        }
        private global::System.DateTime _CreatedAt;
        partial void OnCreatedAtChanging(global::System.DateTime value);
        partial void OnCreatedAtChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastActivityDate
        {
            get
            {
                return _LastActivityDate;
            }
            set
            {
                OnLastActivityDateChanging(value);
                ReportPropertyChanging("LastActivityDate");
                _LastActivityDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastActivityDate");
                OnLastActivityDateChanged();
            }
        }
        private global::System.DateTime _LastActivityDate;
        partial void OnLastActivityDateChanging(global::System.DateTime value);
        partial void OnLastActivityDateChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AuthenticationId
        {
            get
            {
                return _AuthenticationId;
            }
            set
            {
                OnAuthenticationIdChanging(value);
                ReportPropertyChanging("AuthenticationId");
                _AuthenticationId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AuthenticationId");
                OnAuthenticationIdChanged();
            }
        }
        private global::System.Int32 _AuthenticationId;
        partial void OnAuthenticationIdChanging(global::System.Int32 value);
        partial void OnAuthenticationIdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__UserDevic__Authe__20C1E124", "Authentication")]
        public Authentication Authentication
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Authentication>("BanquetesElijaModel.FK__UserDevic__Authe__20C1E124", "Authentication").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Authentication>("BanquetesElijaModel.FK__UserDevic__Authe__20C1E124", "Authentication").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Authentication> AuthenticationReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Authentication>("BanquetesElijaModel.FK__UserDevic__Authe__20C1E124", "Authentication");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Authentication>("BanquetesElijaModel.FK__UserDevic__Authe__20C1E124", "Authentication", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__UserDevic__Devic__21B6055D", "Device")]
        public Device Device
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("BanquetesElijaModel.FK__UserDevic__Devic__21B6055D", "Device").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("BanquetesElijaModel.FK__UserDevic__Devic__21B6055D", "Device").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Device> DeviceReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Device>("BanquetesElijaModel.FK__UserDevic__Devic__21B6055D", "Device");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Device>("BanquetesElijaModel.FK__UserDevic__Devic__21B6055D", "Device", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BanquetesElijaModel", "FK__UserDevic__UserI__22AA2996", "User")]
        public User User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BanquetesElijaModel.FK__UserDevic__UserI__22AA2996", "User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BanquetesElijaModel.FK__UserDevic__UserI__22AA2996", "User").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<User> UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<User>("BanquetesElijaModel.FK__UserDevic__UserI__22AA2996", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<User>("BanquetesElijaModel.FK__UserDevic__UserI__22AA2996", "User", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
